// Generated by gencpp from file serial/wheelSpeed.msg
// DO NOT EDIT!


#ifndef SERIAL_MESSAGE_WHEELSPEED_H
#define SERIAL_MESSAGE_WHEELSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial
{
template <class ContainerAllocator>
struct wheelSpeed_
{
  typedef wheelSpeed_<ContainerAllocator> Type;

  wheelSpeed_()
    : wheelSpeed1(0)
    , wheelSpeed2(0)
    , wheelSpeed3(0)
    , wheelSpeed4(0)  {
    }
  wheelSpeed_(const ContainerAllocator& _alloc)
    : wheelSpeed1(0)
    , wheelSpeed2(0)
    , wheelSpeed3(0)
    , wheelSpeed4(0)  {
  (void)_alloc;
    }



   typedef int32_t _wheelSpeed1_type;
  _wheelSpeed1_type wheelSpeed1;

   typedef int32_t _wheelSpeed2_type;
  _wheelSpeed2_type wheelSpeed2;

   typedef int32_t _wheelSpeed3_type;
  _wheelSpeed3_type wheelSpeed3;

   typedef int32_t _wheelSpeed4_type;
  _wheelSpeed4_type wheelSpeed4;





  typedef boost::shared_ptr< ::serial::wheelSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial::wheelSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct wheelSpeed_

typedef ::serial::wheelSpeed_<std::allocator<void> > wheelSpeed;

typedef boost::shared_ptr< ::serial::wheelSpeed > wheelSpeedPtr;
typedef boost::shared_ptr< ::serial::wheelSpeed const> wheelSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial::wheelSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial::wheelSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'serial': ['/home/ubuntu/zky_robot/src/serial/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial::wheelSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial::wheelSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b667162500357f28e5525489e16c54f";
  }

  static const char* value(const ::serial::wheelSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b667162500357f2ULL;
  static const uint64_t static_value2 = 0x8e5525489e16c54fULL;
};

template<class ContainerAllocator>
struct DataType< ::serial::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial/wheelSpeed";
  }

  static const char* value(const ::serial::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 wheelSpeed1\n\
int32 wheelSpeed2\n\
int32 wheelSpeed3\n\
int32 wheelSpeed4\n\
\n\
";
  }

  static const char* value(const ::serial::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial::wheelSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wheelSpeed1);
      stream.next(m.wheelSpeed2);
      stream.next(m.wheelSpeed3);
      stream.next(m.wheelSpeed4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheelSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial::wheelSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial::wheelSpeed_<ContainerAllocator>& v)
  {
    s << indent << "wheelSpeed1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheelSpeed1);
    s << indent << "wheelSpeed2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheelSpeed2);
    s << indent << "wheelSpeed3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheelSpeed3);
    s << indent << "wheelSpeed4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheelSpeed4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_MESSAGE_WHEELSPEED_H
